In [2]:
import pandas as pd

In [6]:
app = pd.read_csv('jan23_applications.csv')
app

,EP ID,Status,Home LC,Home MC,Home Region,OP ID,Product,Work Field,SDG Goal,SDG Target,...,utm_medium,utm_source,utm_content,utm_campaign,Tags,APL ID,Global Project,Global Partner,Company Name,Branch Name
0,000281faa05c064092497533cc4c854c,open,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289392,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6409972,False,False,VirtualSoft Technologies Pvt Ltd.,Chandigarh
1,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1282746,GV (New),NaN,8.0,8.6,...,"""""","""""","""""","""""",NaN,6380081,False,False,AARS Design,Mumbai
2,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1282747,GV (New),NaN,4.0,4.6,...,"""""","""""","""""","""""",NaN,6380323,False,False,Sujata Adarsh Foundation,Mumbai
3,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289195,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6409974,False,False,"Vellore Institute of Technology, Vellore",Chennai
4,000281faa05c064092497533cc4c854c,withdrawn,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1285692,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6372779,False,False,Tonic Worldwide,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84738,fffbd3b49ef6bd916995f2754104d0eb,rejected,İZMİR,Turkey,Europe,1291326,GTa,Business Administration,NaN,NaN,...,"""""","""""","""""","""""",NaN,6422948,False,True,Deutsche Post DHL Group,DHL UAE
84739,fffbd3b49ef6bd916995f2754104d0eb,withdrawn,İZMİR,Turkey,Europe,1288369,GTe,NaN,NaN,NaN,...,"""""","""""","""""","""""",NaN,6420688,False,False,American School Way,Bogotá
84740,fffcc1f3b2e7c1dcbec944fb845af4a1,open,Cairo University,Egypt,Middle East and Africa,1279532,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6419905,False,False,Unicosmos School,Adarsh Educational Society
84741,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1261791,GTa,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6372436,False,False,DesignPr,Eskişehir
84742,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1287703,GTa,Marketing,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6376654,False,False,Gads Online Marketing,Cluj-Napoca

In [10]:
#remobe GV (New)
# remove rows by filtering
app = app[app['Product'] != 'GV (New)']
# display the dataframe
app

,EP ID,Status,Home LC,Home MC,Home Region,OP ID,Product,Work Field,SDG Goal,SDG Target,...,utm_medium,utm_source,utm_content,utm_campaign,Tags,APL ID,Global Project,Global Partner,Company Name,Branch Name
0,000281faa05c064092497533cc4c854c,open,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289392,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6409972,False,False,VirtualSoft Technologies Pvt Ltd.,Chandigarh
3,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289195,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6409974,False,False,"Vellore Institute of Technology, Vellore",Chennai
4,000281faa05c064092497533cc4c854c,withdrawn,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1285692,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6372779,False,False,Tonic Worldwide,Mumbai
6,000619cc73c5728e1a49948c18c423c6,open,Lahore,Pakistan,Asia Pacific,1262154,GTa,Information Technology,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6410798,False,False,DUAL Systems Hungary Ltd.,DUAL Systems Hungary Ltd.
7,000619cc73c5728e1a49948c18c423c6,rejected,Lahore,Pakistan,Asia Pacific,1290573,GTa,Information Technology,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6405195,False,True,Deutsche Post DHL Group,Deutsche Post DHL Group - Bonn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84738,fffbd3b49ef6bd916995f2754104d0eb,rejected,İZMİR,Turkey,Europe,1291326,GTa,Business Administration,NaN,NaN,...,"""""","""""","""""","""""",NaN,6422948,False,True,Deutsche Post DHL Group,DHL UAE
84739,fffbd3b49ef6bd916995f2754104d0eb,withdrawn,İZMİR,Turkey,Europe,1288369,GTe,NaN,NaN,NaN,...,"""""","""""","""""","""""",NaN,6420688,False,False,American School Way,Bogotá
84740,fffcc1f3b2e7c1dcbec944fb845af4a1,open,Cairo University,Egypt,Middle East and Africa,1279532,GTa,Marketing,NaN,NaN,...,"""""","""""","""""","""""",NaN,6419905,False,False,Unicosmos School,Adarsh Educational Society
84741,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1261791,GTa,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6372436,False,False,DesignPr,Eskişehir
84742,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1287703,GTa,Marketing,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6376654,False,False,Gads Online Marketing,Cluj-Napoca

In [19]:
app_final = app.drop(columns=['SDG Goal',
                  'SDG Target',
                  'utm_term',
                  'utm_medium',
                  'utm_source',
                  'utm_content',
                  'utm_campaign',
                  'Tags',
                  'Global Project',
                  'Global Partner'])

app_final

,EP ID,Status,Home LC,Home MC,Home Region,OP ID,Product,Work Field,Semi-Remote OP,Duration Type,...,Date Applied,Date Accepted,Date Rejected,Date Approved,Date Realized,Date Finished,Campaign ID,APL ID,Company Name,Branch Name
0,000281faa05c064092497533cc4c854c,open,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289392,GTa,Marketing,False,Long-term,...,2022-11-09 22:47:43,NaN,NaN,NaN,NaN,NaN,NaN,6409972,VirtualSoft Technologies Pvt Ltd.,Chandigarh
3,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289195,GTa,Marketing,False,Short-term,...,2022-11-09 22:57:45,NaN,2022-11-23 09:13,NaN,NaN,NaN,NaN,6409974,"Vellore Institute of Technology, Vellore",Chennai
4,000281faa05c064092497533cc4c854c,withdrawn,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1285692,GTa,Marketing,False,Long-term,...,2022-08-05 11:29:10,NaN,NaN,NaN,NaN,NaN,NaN,6372779,Tonic Worldwide,Mumbai
6,000619cc73c5728e1a49948c18c423c6,open,Lahore,Pakistan,Asia Pacific,1262154,GTa,Information Technology,False,Long-term,...,2022-11-11 20:42:02,NaN,NaN,NaN,NaN,NaN,NaN,6410798,DUAL Systems Hungary Ltd.,DUAL Systems Hungary Ltd.
7,000619cc73c5728e1a49948c18c423c6,rejected,Lahore,Pakistan,Asia Pacific,1290573,GTa,Information Technology,False,Long-term,...,2022-10-30 13:06:02,NaN,2022-11-14 10:00,NaN,NaN,NaN,NaN,6405195,Deutsche Post DHL Group,Deutsche Post DHL Group - Bonn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84738,fffbd3b49ef6bd916995f2754104d0eb,rejected,İZMİR,Turkey,Europe,1291326,GTa,Business Administration,False,Long-term,...,2022-12-08 07:38:18,NaN,2022-12-21 10:08,NaN,NaN,NaN,NaN,6422948,Deutsche Post DHL Group,DHL UAE
84739,fffbd3b49ef6bd916995f2754104d0eb,withdrawn,İZMİR,Turkey,Europe,1288369,GTe,NaN,False,Long-term,...,2022-12-02 07:50:02,NaN,NaN,NaN,NaN,NaN,NaN,6420688,American School Way,Bogotá
84740,fffcc1f3b2e7c1dcbec944fb845af4a1,open,Cairo University,Egypt,Middle East and Africa,1279532,GTa,Marketing,False,Long-term,...,2022-11-30 17:18:12,NaN,NaN,NaN,NaN,NaN,NaN,6419905,Unicosmos School,Adarsh Educational Society
84741,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1261791,GTa,Other,False,Short-term,...,2022-08-04 11:13:08,NaN,2022-09-29 15:56,NaN,NaN,NaN,NaN,6372436,DesignPr,Eskişehir
84742,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1287703,GTa,Marketing,False,Short-term,...,2022-08-17 12:15:16,NaN,2022-08-26 09:30,NaN,NaN,NaN,NaN,6376654,Gads Online Marketing,Cluj-Napoca

In [21]:
pbg = pd.read_csv('jan23_People-backgrounds.csv')
pbg

,EP ID,Status,Background,Gender,Age,Signed Up,Home LC,Home MC,Home Region
0,0113ceeaca1a9483e552b49ef556cb96,rejected,Business administration,Male,30.20,2022-07-01,Dasmariñas,Philippines,Asia Pacific
1,02e749a9d063d73eaaa4894b05eb9e9a,rejected,Business administration | Industrial engineering,female,26.67,2022-07-01,MC Costa Rica,Costa Rica,Americas
2,07ae23c2fdbab6bdab91131953a585d5,rejected,Computer engineering | Computer sciences,female,22.51,2022-07-01,ISTANBUL WEST,Turkey,Europe
3,0d104f6e2569647c4005b58d059883a1,rejected,Accounting | Finance,female,24.83,2022-07-01,Oran,Algeria,Middle East and Africa
4,107fa2d75077ac8de80c87c0efb87b9d,rejected,Business administration,Male,24.23,2022-07-01,Carthage,Tunisia,Middle East and Africa
...,...,...,...,...,...,...,...,...,...
13888,deb6017bde317ffc2686cd3fa3a48ae3,open,Business administration | Logistics | Sales,male,29.00,2023-02-06,India National Office,India,Asia Pacific
13889,ea0e5cdbbd50f7284afaf5a15fe7300d,accepted,International relations,female,21.97,2023-02-06,KOCAELI,Turkey,Europe
13890,f580095dc7857ce944662e5744ae7a5c,open,Computer sciences,female,25.79,2023-02-06,Cairo University,Egypt,Middle East and Africa
13891,f580095dc7857ce944662e5744ae7a5c,rejected,Computer sciences,female,25.79,2023-02-06,Cairo University,Egypt,Middle East and Africa
13892,f5a96f85ab45d6a8ced17742763040fe,open,Electrical engineering | Languages,female,25.10,2023-02-06,Mumbai,India,Asia Pacific

In [22]:
ps = pd.read_csv('jan23_People-skills.csv')
ps

,EP ID,Home LC,Home MC,Home Region,Interest in GV,Interest in GTa,Interest in GTe,Skills
0,e8c8b11d2902ce069d9bb27d26ed696f,Constantine,Algeria,Middle East and Africa,False,False,False,Mac usage | Beginner
1,a98e8c0c63f2cb7c9d8b537244f5b550,SAN JOSE,United States,Americas,False,True,False,Professional Skills | Advanced; Adaptability |...
2,107fa2d75077ac8de80c87c0efb87b9d,Carthage,Tunisia,Middle East and Africa,False,False,False,Controlling | Intermediate; Internet usage | A...
3,0d104f6e2569647c4005b58d059883a1,Oran,Algeria,Middle East and Africa,False,False,False,Microsoft Excel | Advanced; Photoshop | Beginn...
4,004fa4265748f0fe017a4dbb97cd1293,Oran,Algeria,Middle East and Africa,False,False,True,Microsoft Word | Advanced; Event Planning | Ad...
...,...,...,...,...,...,...,...,...
18785,3df29e02ddebe9960f90de730a61b2d7,Dehradun,India,Asia Pacific,False,True,False,Adaptability | Advanced
18786,fa75d86f80604391623f40237bacaa03,Bejaia,Algeria,Middle East and Africa,False,False,False,Construction Management | Beginner; Adaptabili...
18787,d7c03f6a7485cde346ade1b17e31dad8,ISTANBUL,Turkey,Europe,False,False,False,Database Administration | Beginner; Data Manag...
18788,8fb1d0f84938f06768104c4cc17e4361,EASTERN MEDITERRANEAN,Turkey,Europe,False,True,False,Microsoft Excel | Advanced; Microsoft Powerpoi...
18789,fa5228a56439cb7f1191216b71bfd9e4,Ain Shams University,Egypt,Middle East and Africa,False,False,False,Client servicing | Advanced; Analytical thinki...

In [28]:
app_pbg = pd.merge(app_final, pbg, on = ["EP ID","Home LC","Home MC","Home Region"], how = "left")

app_pbg

,EP ID,Status_x,Home LC,Home MC,Home Region,OP ID,Product,Work Field,Semi-Remote OP,Duration Type,...,Date Finished,Campaign ID,APL ID,Company Name,Branch Name,Status_y,Background,Gender,Age,Signed Up
0,000281faa05c064092497533cc4c854c,open,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289392,GTa,Marketing,False,Long-term,...,NaN,NaN,6409972,VirtualSoft Technologies Pvt Ltd.,Chandigarh,open,Marketing | Sales,female,22.92,2022-08-02
1,000281faa05c064092497533cc4c854c,open,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289392,GTa,Marketing,False,Long-term,...,NaN,NaN,6409972,VirtualSoft Technologies Pvt Ltd.,Chandigarh,rejected,Marketing | Sales,female,22.92,2022-08-02
2,000281faa05c064092497533cc4c854c,open,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289392,GTa,Marketing,False,Long-term,...,NaN,NaN,6409972,VirtualSoft Technologies Pvt Ltd.,Chandigarh,withdrawn,Marketing | Sales,female,22.92,2022-08-02
3,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289195,GTa,Marketing,False,Short-term,...,NaN,NaN,6409974,"Vellore Institute of Technology, Vellore",Chennai,open,Marketing | Sales,female,22.92,2022-08-02
4,000281faa05c064092497533cc4c854c,rejected,COCODY-ABIDJAN,Cote D'Ivoire,Middle East and Africa,1289195,GTa,Marketing,False,Short-term,...,NaN,NaN,6409974,"Vellore Institute of Technology, Vellore",Chennai,rejected,Marketing | Sales,female,22.92,2022-08-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85681,fffbd3b49ef6bd916995f2754104d0eb,withdrawn,İZMİR,Turkey,Europe,1288369,GTe,NaN,False,Long-term,...,NaN,NaN,6420688,American School Way,Bogotá,rejected,Business administration | Political science | ...,male,23.76,2022-11-28
85682,fffbd3b49ef6bd916995f2754104d0eb,withdrawn,İZMİR,Turkey,Europe,1288369,GTe,NaN,False,Long-term,...,NaN,NaN,6420688,American School Way,Bogotá,withdrawn,Business administration | Political science | ...,male,23.76,2022-11-28
85683,fffcc1f3b2e7c1dcbec944fb845af4a1,open,Cairo University,Egypt,Middle East and Africa,1279532,GTa,Marketing,False,Long-term,...,NaN,NaN,6419905,Unicosmos School,Adarsh Educational Society,open,Marketing,Male,24.76,2022-11-30
85684,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1261791,GTa,Other,False,Short-term,...,NaN,NaN,6372436,DesignPr,Eskişehir,rejected,Design,female,28.22,2022-08-04
85685,fffd0db8cbc5f27f67f3e0e40b951204,rejected,MSA,Egypt,Middle East and Africa,1287703,GTa,Marketing,False,Short-term,...,NaN,NaN,6376654,Gads Online Marketing,Cluj-Napoca,rejected,Design,female,28.22,2022-08-04

In [32]:
app_pbg_ps = pd.merge(app_pbg, ps, on = ["EP ID","Home LC","Home MC","Home Region"], how = "left")

app_pbg_ps

d:\INSTALLED\Conda\lib\site-packages\IPython\lib\pretty.py:700: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  output = repr(obj)
d:\INSTALLED\Conda\lib\site-packages\IPython\core\formatters.py:345: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  return method()

,EP ID,Status_x,Home LC,Home MC,Home Region,OP ID,Product,Work Field,Semi-Remote OP,Duration Type,...,Branch Name,Status_y,Background,Gender,Age,Signed Up,Interest in GV,Interest in GTa,Interest in GTe,Skills
0,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1285407,GTa,Information Technology,False,Long-term,...,Koding Kingdom (Hong Kong) Limited,open,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
1,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1285407,GTa,Information Technology,False,Long-term,...,Koding Kingdom (Hong Kong) Limited,rejected,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
2,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1285407,GTa,Information Technology,False,Long-term,...,Koding Kingdom (Hong Kong) Limited,withdrawn,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
3,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1287280,GTa,Information Technology,True,Long-term,...,Level 33 Indústria e Comércio,open,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
4,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1287280,GTa,Information Technology,True,Long-term,...,Level 33 Indústria e Comércio,rejected,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,fd2ae62c8480078ee6345327e8cdeb0d,rejected,COLOMBO NORTH,Sri Lanka,Asia Pacific,1290596,GTa,Finance,False,Long-term,...,Electrolux Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2258,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1282736,GTa,Marketing,False,Long-term,...,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2259,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1287308,GTa,Business Development,False,Long-term,...,Chennai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1287310,GTa,Business Development,False,Long-term,...,İstanbul - Beyoğlu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2261,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1288102,GTa,Marketing,False,Long-term,...,Utrecht,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
app_pbg_ps = app_pbg_ps[app_pbg_ps['Home MC'] == 'Sri Lanka']
# display the dataframe
app_pbg_ps

,EP ID,Status_x,Home LC,Home MC,Home Region,OP ID,Product,Work Field,Semi-Remote OP,Duration Type,...,Branch Name,Status_y,Background,Gender,Age,Signed Up,Interest in GV,Interest in GTa,Interest in GTe,Skills
0,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1285407,GTa,Information Technology,False,Long-term,...,Koding Kingdom (Hong Kong) Limited,open,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
1,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1285407,GTa,Information Technology,False,Long-term,...,Koding Kingdom (Hong Kong) Limited,rejected,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
2,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1285407,GTa,Information Technology,False,Long-term,...,Koding Kingdom (Hong Kong) Limited,withdrawn,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
3,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1287280,GTa,Information Technology,True,Long-term,...,Level 33 Indústria e Comércio,open,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
4,0084c73bae1b494abc0395b72ad1a38e,open,USJ,Sri Lanka,Asia Pacific,1287280,GTa,Information Technology,True,Long-term,...,Level 33 Indústria e Comércio,rejected,Biology | Chemistry | Computer engineering | C...,female,25.64,2022-10-17,False,True,False,Android | Advanced; Python | Intermediate; Str...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,fd2ae62c8480078ee6345327e8cdeb0d,rejected,COLOMBO NORTH,Sri Lanka,Asia Pacific,1290596,GTa,Finance,False,Long-term,...,Electrolux Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2258,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1282736,GTa,Marketing,False,Long-term,...,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2259,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1287308,GTa,Business Development,False,Long-term,...,Chennai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1287310,GTa,Business Development,False,Long-term,...,İstanbul - Beyoğlu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2261,ff373ecce5a96cad76f5ee2bec7acf22,rejected,COLOMBO SOUTH,Sri Lanka,Asia Pacific,1288102,GTa,Marketing,False,Long-term,...,Utrecht,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
app_pbg_ps.to_csv('application_people_skills_background.csv')